dataset_path: !!python/object/apply:pathlib.PosixPath
- data
- nerf_synthetic
- ficus
dataset_type: blender
debug_render_interval: null
eval_final_samples: 48
eval_proposal_samples: &id001 !!python/tuple
- 256
- 128
field.density_decoder.density_activation: trunc_exp
field.density_decoder.name: null
field.density_decoder.parent: null
field.grid_type: vm
field.primary_channels: 192
field.primary_decoder.camera_embed_dim: 0
field.primary_decoder.color_layers: 2
field.primary_decoder.color_units: 128
field.primary_decoder.density_activation: trunc_exp
field.primary_decoder.feature_n_freqs: 0
field.primary_decoder.name: null
field.primary_decoder.parent: null
field.primary_decoder.viewdir_n_freqs: 0
field.primary_decoder.viewdir_sph_harm_levels: 4
field.primary_resolutions: !!python/tuple
- 64
- 128
- 256
- 512
field.proposal_channels: !!python/tuple
- 48
- 48
field.proposal_resolutions: !!python/tuple
- 64
- 128
grid_bound: 1.6
optim.camera_delta_lr: 0.0
optim.camera_delta_steps: 5000
optim.decoder_lr: 0.01
optim.distortion_loss_coeff: 0.001
optim.factor_lr: 0.01
optim.half_resolution_steps: 0
optim.interlevel_loss_coeff: 1.0
optim.l12_reg_coeff: 0.0
optim.low_pass_steps: 512
optim.minibatch_size: 4096
optim.projection_decay_start: 500
optim.projection_decay_steps: 4500
optim.projection_lr: 0.0
optim.proposal_anneal_iters: 1000
optim.proposal_anneal_slope: 10.0
optim.total_steps: 30000
optim.tv_reg_l1_coeff: 0.0
optim.tv_reg_l2_coeff: 0.0
optim.warmup_steps: 512
primary_transform_count: 8
proposal_transform_count: null
render_config.background: white
render_config.far: 6.0
render_config.final_samples: 48
render_config.global_rotate_seed: null
render_config.gradient_scaling: false
render_config.histogram_padding: 0.01
render_config.initial_samples: linear
render_config.near: 2.0
render_config.proposal_samples: *id001
render_config.sample_aabb_max: !!python/tuple
- 1.0
- 1.0
- 1.0
render_config.sample_aabb_min: !!python/tuple
- -1.0
- -1.0
- -1.0
seed: 0
tau_init: random
unbounded_contraction_norm: inf
