python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/aspen
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/bww_entrance
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/campanile
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/desolation
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/dozer
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/Egypt
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/floating-tree
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/Giannini-Hall
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/kitchen
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/library
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/person
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/plane
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/poster
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/redwoods2
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/storefront
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/sculpture
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/stump
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/vegetation
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/aspen
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/bww_entrance
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/campanile
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/desolation
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/dozer
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/Egypt
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/floating-tree
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/Giannini-Hall
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/kitchen
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/library
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/person
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/plane
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/poster
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/redwoods2
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/storefront
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/sculpture
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/stump
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/vegetation
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/aspen
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/bww_entrance
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/campanile
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/desolation
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/dozer
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/Egypt
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/floating-tree
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/Giannini-Hall
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/kitchen
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/library
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/person
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/plane
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/poster
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/redwoods2
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/storefront
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/sculpture
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/stump
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/vegetation
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/aspen
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/bww_entrance
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/campanile
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/desolation
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/dozer
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/Egypt
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/floating-tree
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/Giannini-Hall
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/kitchen
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/library
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/person
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/plane
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/poster
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/redwoods2
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/storefront
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/sculpture
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/stump
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/vegetation
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/aspen
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/bww_entrance
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/campanile
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/desolation
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/dozer
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/Egypt
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/floating-tree
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/Giannini-Hall
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/kitchen
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/library
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/person
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/plane
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/poster
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/redwoods2
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/storefront
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/sculpture
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/stump
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/vegetation
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/aspen
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/bww_entrance
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/campanile
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/desolation
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/dozer
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/Egypt
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/floating-tree
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/Giannini-Hall
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/kitchen
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/library
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/person
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/plane
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/poster
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/redwoods2
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/storefront
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/sculpture
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/stump
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/vegetation
