python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/aspen --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/bww_entrance --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/campanile --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/desolation --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/dozer --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/Egypt --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/floating-tree --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/Giannini-Hall --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/kitchen --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/library --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/person --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/plane --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/poster --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/redwoods2 --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/storefront --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/sculpture --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/stump --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-axis-aligned --dataset-path ./data/nerfstudio/vegetation --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/aspen --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/bww_entrance --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/campanile --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/desolation --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/dozer --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/Egypt --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/floating-tree --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/Giannini-Hall --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/kitchen --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/library --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/person --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/plane --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/poster --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/redwoods2 --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/storefront --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/sculpture --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/stump --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-4t --dataset-path ./data/nerfstudio/vegetation --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/aspen --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/bww_entrance --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/campanile --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/desolation --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/dozer --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/Egypt --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/floating-tree --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/Giannini-Hall --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/kitchen --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/library --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/person --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/plane --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/poster --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/redwoods2 --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/storefront --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/sculpture --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/stump --field.primary-channels 128
python train_nerf.py nerfstudio-kplane-64c-tilted-8t --dataset-path ./data/nerfstudio/vegetation --field.primary-channels 128
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/aspen --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/bww_entrance --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/campanile --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/desolation --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/dozer --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/Egypt --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/floating-tree --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/Giannini-Hall --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/kitchen --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/library --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/person --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/plane --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/poster --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/redwoods2 --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/storefront --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/sculpture --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/stump --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-axis-aligned --dataset-path ./data/nerfstudio/vegetation --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/aspen --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/bww_entrance --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/campanile --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/desolation --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/dozer --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/Egypt --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/floating-tree --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/Giannini-Hall --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/kitchen --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/library --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/person --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/plane --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/poster --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/redwoods2 --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/storefront --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/sculpture --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/stump --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-4t --dataset-path ./data/nerfstudio/vegetation --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/aspen --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/bww_entrance --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/campanile --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/desolation --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/dozer --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/Egypt --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/floating-tree --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/Giannini-Hall --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/kitchen --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/library --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/person --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/plane --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/poster --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/redwoods2 --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/storefront --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/sculpture --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/stump --field.primary-channels 384
python train_nerf.py nerfstudio-vm-192c-tilted-8t --dataset-path ./data/nerfstudio/vegetation --field.primary-channels 384
